version: '3.8'
name: IO_2024

services:
  iodb:
    image: postgres:17
    container_name: io_db
    restart: always
    environment:
      POSTGRES_DB: iodb
      POSTGRES_USER: io
      POSTGRES_PASSWORD: iopassword
    ports:
      - 5432:5432
    volumes:
      - iopg:/var/lib/postgresql/data
volumes:
  iopg: