name: IO_2024

services:
  postgresql:
    container_name: io_db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 54329:5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:

networks:
  default:
    name: io_db_network
