name: Pylint

on: 
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: "3.12"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8

    - name: Run Pylint
      run: |
        python -m pylint $(git ls-files '*.py') | \
        awk -F ":" '{ print $0 } /[^:]+:[0-9]+:[0-9]+ [A-Z0-9]+: / {print "::error file="substr($1, 3)", line="$2", col="$3"::"$4":"$5 }';

    - name: Run flake8
      run: |
        flake8 $(git ls-files '*.py') | \
        awk -F ":" '{ print $0 } NF >= 4 {print "::error file="substr($1, 3)", line="$2", col="$3"::"$4" }';
