name: Python Checks (Pylint, Flake8)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: [ "3.12" ]
    timeout-minutes: 1
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8

    - name: Run Pylint
      run: |
        python -m pylint $(git ls-files '*.py') \
        --msg-template="::error::{path}:{line}:{column}: {msg_id} ({symbol})%0A{msg}"

    - name: Run Flake8
      run: |
        python -m flake8 $(git ls-files '*.py') \
        --format="::error::%(path)s:%(row)d:%(col)d: %(code)s%0A%(text)s"
